# Goal definition
geometry_msgs/Pose target_pose
bool is_constrain
float32 x_axis_tolerance
float32 y_axis_tolerance
float32 z_axis_tolerance

---
# Result definition
bool success
string message

---
# Feedback definition
string current_pose