/pipettle/controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    pipettle_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    pipettle_joint_controllers:
      type: joint_trajectory_controller/JointTrajectoryController

/pipettle/pipettle_joint_controllers:
  ros__parameters:
    joints:
      - pipettle_base2link
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0